name: Lakshore
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  intl: ^0.18.0
  toggle_switch: ^2.0.1
  email_validator: ^2.0.1
  readmore: ^2.2.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "asset/playstore.png"

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/arrow.riv
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins.ttf

